### ISSUE TITLE
Windows 0.4.4 hänger sig, kanske därför att nyhetsflödet inte går att nå

### ISSUE THREAD

**Issue by d-d** [jackuess/pirateplayer#2]
Idag verkar det inte gå att nå domänen där nyhetsflödet ligger.  Tyvärr gör det att hela appen hänger sig. Det står "laddar nyheter..."  och efter några minuter kraschar programmet-
Windows 0.4.4

**Comment by jackuess** [comment]
Fixat sedan 0.4.5! Tack för rapporten!
