### ISSUE TITLE
Kompilera på ubuntu 12.10 64 bit

### ISSUE THREAD

**Issue by netmate1234** [jackuess/pirateplayer#3]
Jag kan inte kompilera på ubuntu 12.10 64 bit.

sudo make install -C build/gmake/
För tidy-html5 går bra.

Medans:
sh build/gnuauto/setup.sh && ./configure && make
ger:
You need libtoolize to continue

libtoolize finns inte i reposetoryn.

make för pirateplayer
ger ett error:
In file included from src/network/piratenetworkaccessmanager.cpp:6:0:
src/network/tidynetworkreply.h:4:18: fatal error: tidy.h: No such file or directory
compilation terminated.
make: **\* [build/obj/piratenetworkaccessmanager.o] Error 1

**Comment by jackuess** [comment]
Libtoolize ingår i Libtool-paketet.

Har du lust att fixa ett deb-paket för 64-bitars om du nu kompilerar? Mejla mig på jacques snabela pirateplay.se i så fall. Vore grymt!

**Comment by netmate1234** [comment]
Tack för snabbt svar :)

Jag kan kan kanske försöka fixa ett deb paket, men först måste få igång applikationen.

Libtool paketet är inne.

Jag var tvungen att kopiera in buffio.h, platform.h, tidy.h, tidyenum.h från tidy-html5 till /usr/include för att få kompileringen att gå igenom.
((ubuntus tidy packet läger dem per default i /usr/include/tidy))

När jag kör pirateplayer får jag:
pirateplayer 
Setting addon directory: "/home/m/.local/share/data/wrutschkow/pirateplayer/addons/browse" 
file:///home/m/.local/share/data/wrutschkow/pirateplayer/addons/browse/main.qml:2:1: module "QtDesktop" is not installed 
     import QtDesktop 0.1 
     ^ 
Segmentation fault (core dumped)

Kanske något som saknas i Makefile?

Har du något uppslag?

**Comment by jackuess** [comment]
Du behöver [Qt-components-desktop](https://launchpad.net/~forumnokia/+archive/fn-ppa/+packages). Har tydligen glömt att nämna det som beroende i Readmen.

Jag använde [Checkinstall](https://help.ubuntu.com/community/CheckInstall) när jag byggde deb-paket, om du inte redan känner till det - riktigt smidigt.

**Comment by netmate1234** [comment]
Att installera https://launchpad.net/~forumnokia/+archive/fn-ppa/+files/qt-components-desktop_0.2~git20120611-1-0fn_amd64.deb hjälpte

Nu är det något annat problem... (Vill först säga att jag inte fått in tidy-html5 rätt om det nu påverkar, just nu verkar det vara någon kombination av tidy-html5 och ubuntus deb tidy)

Efter att applikationen startat går jag till bläddra, väljer svtplay och då får jag:
link id1242 hasn't been detected!
Segmentation fault (core dumped)

(jag tror det var att jag gick in på tv4play och då:
Error FODC0002 in tag:trolltech.com,2007:QtXmlPatterns:QIODeviceVariable:src, at line 1, column 41: Encoding us-ascii is unsupported
Segmentation fault (core dumped)
)

Kan tidy vara involverat i det här, eller tror du att det beror på något annat?

När jag provar att ladda ner får jag "Ett fel uppstod"

**Comment by jackuess** [comment]
Låter som du installerat tidy-html5, men inte libtidy-html5. Läs under rubriken "Building the libtidy shared library" i [tidy-html5-readme:n](https://github.com/w3c/tidy-html5#readme).

> När jag provar att ladda ner får jag "Ett fel uppstod"

Har du installerat Ffmpeg enligt [installations-instruktionerna](http://pirateplay.se/player.html#install)?

**Comment by netmate1234** [comment]
Hej.

Det verkar som ffmpeg (från ppa:jon-severinsson/ffmpeg) trasar vdpau på ubuntu 12.10. Jag har mailat Jon. (Jag hittade inte var jag kunde göra en bug rapport.
