### ISSUE TITLE
Runtime error: 'module "QtDesktop" is not installed'

### ISSUE THREAD

**Issue by leamas** [jackuess/pirateplayer#5]
Getting runtime error:

file://~/.local/share/data/wrutschkow/pirateplayer/addons/browse/main.qml:2:1: module "QtDesktop" is not installed 
     import QtDesktop 0.1

This seems to be introduced by (previous commit is OK)

386f65f Added simple addon framework

Fedora 17, qt 4.8.3-7

**Comment by jackuess** [comment]
You need to have [Qt Desktop Components](http://qt-project.org/wiki/QtDesktopComponents) installed.

**Comment by Umeaboy** [comment]
Qt Desktop Components is not released for QT4 so I guess I'll have to wait until Mageia backports QT5 when Mageia 5 is released.

Still getting this error.
