### ISSUE TITLE
v04.6 for MacOSX does not download streams

### ISSUE THREAD

**Issue by bnilsson11** [jackuess/pirateplayer#6]
Used latest (of 23-jan-13) ZIP or git, modified .pro file for mac as such since I use MacPorts for libs:

```
LIBS += -L/usr/lib -L/usr/local/lib -L/opt/local/lib -lrtmp
INCLUDEPATH += /usr/local/include /opt/local/include
```

Built using qtcreator with 65 warnings.
Application runs fine, tried to get a stream from svtplay, Status says "Laddar ned" but there is no network traffic and progress bar will not move.
No errors.

**Comment by jackuess** [comment]
Make sure Ffmpeg is installed - prefably version 1.0.1 - and that Pirateplayer finds it. IIRC Pirateplayer for Mac looks for Ffmpeg in it's own folder, so you should copy ffmpeg to the deployment folder, or the DMG if you're doing  a DMG.

**Comment by bnilsson11** [comment]
Thanks, that did it.

**Comment by jackuess** [comment]
Nice! May I ask what version of Mac OS you are on? So far I've only got confirmation of Pirateplayer 0.4.6 working in OS X 10.8.2.

**Comment by bnilsson11** [comment]
Hi,

Not the latest..

Bengt Nilsson
Ansåsvägen 8
438 53 Hindås
bnilsson11@gmail.com
0301-22150

On 24 jan 2013, at 19:57, Jacques de Laval wrote:

> Nice! May I ask what version of Mac OS you are on? So far I've only got confirmation of Pirateplayer 0.4.6 working in OS X 10.8.2.

Model Name: Mac Pro
  Model Identifier: MacPro1,1
  Processor Name:   Dual-Core Intel Xeon
  Processor Speed:  2.66 GHz
  Number of Processors: 2
  Total Number of Cores:    4
  L2 Cache (per Processor): 4 MB
  Memory:   8 GB
  Bus Speed:    1.33 GHz
  Boot ROM Version: MP11.005D.B00
  SMC Version (system): 1.7f10
  Serial Number (system):   CK74901R09G
  Hardware UUID:    00000000-0000-1000-8000-0017F20F8508

System Version: Mac OS X 10.7.5 (11G63)
  Kernel Version:   Darwin 11.4.2
  Boot Volume:  Macintosh_HD
  Boot Mode:    Normal
  Computer Name:  
  User Name:    Bengt Nilsson (bnilsson)
  Secure Virtual Memory:    Enabled
  64-bit Kernel and Extensions: No

**Comment by jackuess** [comment]
Thanks man!
