### ISSUE TITLE
0.5.0 not working - Fel uppstod

### ISSUE THREAD

**Issue by bnilsson11** [jackuess/pirateplayer#8]
0.5.0 does not download media properly.
When downloading media from svtplay it says "Fel uppstod" and then does nothing.
Haven't tried other sites.

MacPro1,1
OSX 10.7.8

**Comment by yada75** [comment]
Is it on all svt shows or just some?
Can you start from terminal /Applications/pirateplayer.app/Contents/MacOS/pirateplayer
and pate the output here.

**Comment by bnilsson11** [comment]
Hi!

Here:

$ ./pirateplayer 
a 0, 0
a 0, 22
Fmpeg not installed!
Aborting download. 
$
$ pwd
/Applications/Thirdparty/media/pirateplayer0.5.0.app/Contents/MacOS
$ ls -la
total 49880
drwxr-xr-x   6 bnilsson  admin       204 16 Mar 11:26 .
drwxr-xr-x   8 bnilsson  admin       272 16 Mar 11:26 ..
drwxr-xr-x  39 bnilsson  admin      1326 16 Mar 11:26 QtDesktop
-rwxr-xr-x   1 bnilsson  admin  11446852 16 Mar 11:26 ffmpeg
-rwxr-xr-x   1 bnilsson  admin  13861088 16 Mar 11:26 ffplay
-rwxr-xr-x   1 bnilsson  admin    222900 16 Mar 11:26 pirateplayer
$ 

17 mar 2013 kl. 22:38 skrev yada75:

**Comment by jackuess** [comment]
@bnilsson11 When in that directory (/Applications/Thirdparty/media/pirateplayer0.5.0.app/Contents/MacOS) could you try running `./ffmpeg -version` and paste the output here?

**Comment by yada75** [comment]
Guessing by reading history you have built your own pplayer.
if yes.
insert this: qDebug() << "applicationDirPath: "<< QCoreApplication::applicationDirPath() + "/";
in file https://github.com/jackuess/pirateplayer/blob/c7c8ea760bfc80e7e185480734a820e0320196a0/src/network/systemdownload.cpp#L28
before this at row 28:  return QCoreApplication::applicationDirPath() + "/";
clean all and build again.
or if it's the official build try start with absolute path /Applications/Thirdparty/media/pirateplayer0.5.0.app/Contents/MacOS/pirateplayer

**Comment by yada75** [comment]
@bnilsson11 i sent you a custom build with some more debug output, check your gmail

**Comment by yada75** [comment]
Confirmed that supplied ffmpeg and ffplay versions don't work for osx 10.7.
New versions are in the works and will be ready soon with support for 10.7 and 10.8, and thanx @bnilsson11 for helping to test.

**Comment by jackuess** [comment]
Resolved in yada75s [latest build](http://pirateplay.se/pirateplayer/downloads/pirateplayer-0_5_0-2.dmg)
